version: '3.6'
services:

  sandbox-app:
    container_name: 'sandbox-app'
    image: 'sandbox-app'
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=local.sandbox.com
    volumes:
      - ./:/src:delegated
    ports:
      - '3000:3000'
    command: [yarn, 'wds']

  sandbox-nginx:
    container_name: 'sandbox-nginx'
    image: jwilder/nginx-proxy:alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - '80:80'